services:
  - type: web
    name: unsubscribe-server
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -b 0.0.0.0:$PORT unsubscribe:app"
    plan: free
    envVars:
      - key: PORT
        value: 5001
